#!/usr/bin/env python

from hadoop.log import error

error.main()
